{"name": "test_reruns", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = choice([True, False])\n +    where choice = random.choice", "trace": "@pytest.mark.flaky(reruns=3, reruns_delay=2)\n    def test_reruns():\n>       assert random.choice([True, False])\nE       assert False\nE        +  where False = choice([True, False])\nE        +    where choice = random.choice\n\ntests\\pytest\\test_reruns.py:9: AssertionError"}, "start": 1758642466205, "stop": 1758642466205, "uuid": "384355aa-baec-419f-8d5f-9ed06dd00d9f", "historyId": "8a26534d2d9e195af15b0cb6e3498ee0", "testCaseId": "8a26534d2d9e195af15b0cb6e3498ee0", "fullName": "tests.pytest.test_reruns#test_reruns", "labels": [{"name": "tag", "value": "flaky(reruns=3, reruns_delay=2)"}, {"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "host", "value": "McSuit"}, {"name": "thread", "value": "14032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}