{"name": "test_rerun_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = choice([True, False])\n +    where choice = random.choice", "trace": "self = <tests.pytest.test_reruns.TestReruns object at 0x0000027F16F97ED0>\n\n    def test_rerun_2(self):\n>       assert random.choice([True, False])\nE       assert False\nE        +  where False = choice([True, False])\nE        +    where choice = random.choice\n\ntests\\pytest\\test_reruns.py:18: AssertionError"}, "start": 1758642468221, "stop": 1758642468222, "uuid": "87840ccc-4e61-4ce7-8af5-361a17e0402b", "historyId": "df1662c89c40c287908e0e99c9c0d00f", "testCaseId": "df1662c89c40c287908e0e99c9c0d00f", "fullName": "tests.pytest.test_reruns.TestReruns#test_rerun_2", "labels": [{"name": "tag", "value": "flaky(reruns=3, reruns_delay=2)"}, {"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "subSuite", "value": "TestReruns"}, {"name": "host", "value": "McSuit"}, {"name": "thread", "value": "14032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}