{"name": "test_rerun_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = choice([True, False])\n +    where choice = random.choice", "trace": "self = <tests.pytest.test_reruns.TestReruns object at 0x000001C57A9EB890>\n\n    def test_rerun_1(self):\n>       assert random.choice([True, False])\nE       assert False\nE        +  where False = choice([True, False])\nE        +    where choice = random.choice\n\ntests\\pytest\\test_reruns.py:15: AssertionError"}, "start": 1758544961504, "stop": 1758544961505, "uuid": "3633f6b9-703a-41be-87ab-3892cf654cb1", "historyId": "81d6ff8066b3db2379029adbb835c586", "testCaseId": "81d6ff8066b3db2379029adbb835c586", "fullName": "tests.pytest.test_reruns.TestReruns#test_rerun_1", "labels": [{"name": "tag", "value": "flaky(reruns=3, reruns_delay=2)"}, {"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "subSuite", "value": "TestReruns"}, {"name": "host", "value": "McSuit"}, {"name": "thread", "value": "28276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}